export type CommunityStatus = 'Aligned' | 'Partial' | 'Gap' | 'Not found';
export type CommunityRole = 'Workstation' | 'Server' | 'DC';
export type CommunityRoleChoice = 'Auto' | CommunityRole;
export type CommunityOperatingSystem = 'Windows 10' | 'Windows 11' | 'Windows Server 2016' | 'Windows Server 2019' | 'Windows Server 2022' | 'Windows Server 2025' | 'Windows (unspecified)';
export type CommunityOperatingSystemChoice = 'Auto' | CommunityOperatingSystem;
export type CommunityFramework = 'Microsoft' | 'CIS' | 'NIST CSF';

export interface CommunityEventReference {
  id: number;
  name: string;
}

export interface CommunityControl {
  id: string;
  category: string;
  subcategory: string;
  expected: string;
  why: string;
  remediation: string;
  frameworks: readonly CommunityFramework[];
  events: readonly CommunityEventReference[];
  roles?: readonly CommunityRole[];
}

export interface CommunityFinding extends CommunityControl {
  actual: string;
  status: CommunityStatus;
}

export interface CommunityParseStats {
  linesRead: number;
  recognisedSettings: number;
  duplicateSettings: number;
  categoriesSeen: number;
}

export interface CommunityAssessment {
  assetName: string;
  role: CommunityRole;
  operatingSystem: CommunityOperatingSystem;
  roleWasDetected: boolean;
  operatingSystemWasDetected: boolean;
  findings: CommunityFinding[];
  aligned: number;
  partial: number;
  gap: number;
  notFound: number;
  score: number;
  parseStats: CommunityParseStats;
  notices: string[];
}

export interface CommunityAssessmentResult {
  assessment: CommunityAssessment | null;
  errors: string[];
  warnings: string[];
}

export const COMMUNITY_MAX_EVIDENCE_BYTES = 1024 * 1024;

export const communityControls: readonly CommunityControl[] = Object.freeze([
  {
    id: 'COMM-001', category: 'System', subcategory: 'Security System Extension', expected: 'Success',
    why: 'Highlights security package and extension activity that can affect the trusted computing base.',
    remediation: 'Enable Success auditing for Security System Extension through Advanced Audit Policy Configuration.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4610, name: 'Authentication package loaded' }, { id: 4697, name: 'Service installed' }]
  },
  {
    id: 'COMM-002', category: 'System', subcategory: 'System Integrity', expected: 'Success and Failure',
    why: 'Supports visibility of integrity failures, audit loss and important operating-system security state changes.',
    remediation: 'Enable Success and Failure auditing for System Integrity and verify the Security log can retain the resulting events.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 1101, name: 'Audit events dropped' }, { id: 5038, name: 'Code integrity failure' }]
  },
  {
    id: 'COMM-003', category: 'Logon/Logoff', subcategory: 'Logon', expected: 'Success and Failure',
    why: 'Provides the core authentication trail required to investigate successful and unsuccessful sign-ins.',
    remediation: 'Enable Success and Failure auditing for Logon and validate collection of both successful and failed activity.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4624, name: 'Successful logon' }, { id: 4625, name: 'Failed logon' }]
  },
  {
    id: 'COMM-004', category: 'Logon/Logoff', subcategory: 'Logoff', expected: 'Success',
    why: 'Adds session lifecycle context so analysts can distinguish active, disconnected and ended sessions.',
    remediation: 'Enable Success auditing for Logoff through Advanced Audit Policy Configuration.',
    frameworks: ['Microsoft', 'NIST CSF'], events: [{ id: 4634, name: 'Account logged off' }, { id: 4647, name: 'User initiated logoff' }]
  },
  {
    id: 'COMM-005', category: 'Logon/Logoff', subcategory: 'Account Lockout', expected: 'Failure',
    why: 'Supports lockout investigation and can expose password spraying or repeated authentication failures.',
    remediation: 'Enable Failure auditing for Account Lockout and ensure lockout events reach the monitoring platform.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4625, name: 'Failed logon' }, { id: 4740, name: 'Account locked out' }]
  },
  {
    id: 'COMM-006', category: 'Detailed Tracking', subcategory: 'Process Creation', expected: 'Success',
    why: 'Provides high-value execution visibility for investigation, detection and incident reconstruction.',
    remediation: 'Enable Success auditing for Process Creation. Professional guidance also validates command-line enrichment separately.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4688, name: 'New process created' }]
  },
  {
    id: 'COMM-007', category: 'Policy Change', subcategory: 'Audit Policy Change', expected: 'Success',
    why: 'Detects changes that can weaken or alter the security evidence generated by Windows.',
    remediation: 'Enable Success auditing for Audit Policy Change and alert on unexpected policy modifications.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4719, name: 'System audit policy changed' }]
  },
  {
    id: 'COMM-008', category: 'Policy Change', subcategory: 'Authentication Policy Change', expected: 'Success',
    why: 'Provides evidence when authentication and trust-related controls are modified.',
    remediation: 'Enable Success auditing for Authentication Policy Change and review unauthorised changes promptly.',
    frameworks: ['Microsoft', 'NIST CSF'], events: [{ id: 4706, name: 'Domain trust created' }, { id: 4707, name: 'Domain trust removed' }]
  },
  {
    id: 'COMM-009', category: 'Account Management', subcategory: 'User Account Management', expected: 'Success and Failure',
    why: 'Captures account creation, deletion, enablement, disablement and other identity lifecycle activity.',
    remediation: 'Enable Success and Failure auditing for User Account Management.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4720, name: 'User account created' }, { id: 4726, name: 'User account deleted' }]
  },
  {
    id: 'COMM-010', category: 'Account Management', subcategory: 'Security Group Management', expected: 'Success',
    why: 'Highlights changes to security groups that may grant or remove privileged access.',
    remediation: 'Enable Success auditing for Security Group Management and monitor high-impact group membership changes.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4732, name: 'Member added to local group' }, { id: 4733, name: 'Member removed from local group' }]
  },
  {
    id: 'COMM-011', category: 'Account Logon', subcategory: 'Credential Validation', expected: 'Success and Failure',
    why: 'Provides credential validation evidence, especially for NTLM and local account authentication paths.',
    remediation: 'Enable Success and Failure auditing for Credential Validation.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 4776, name: 'Credential validation attempted' }]
  },
  {
    id: 'COMM-012', category: 'DS Access', subcategory: 'Directory Service Changes', expected: 'Success',
    why: 'Provides a selected Domain Controller signal for changes to Active Directory objects.',
    remediation: 'On Domain Controllers, enable Success auditing for Directory Service Changes and configure suitable object auditing.',
    frameworks: ['Microsoft', 'CIS', 'NIST CSF'], events: [{ id: 5136, name: 'Directory object modified' }], roles: ['DC']
  }
]);

const categoryAliases = new Map<string, string>([
  ['system', 'System'],
  ['logon/logoff', 'Logon/Logoff'],
  ['object access', 'Object Access'],
  ['privilege use', 'Privilege Use'],
  ['detailed tracking', 'Detailed Tracking'],
  ['policy change', 'Policy Change'],
  ['account management', 'Account Management'],
  ['ds access', 'DS Access'],
  ['directory service access', 'DS Access'],
  ['account logon', 'Account Logon']
]);

const settingAtEndPattern = /(No\s+Auditing|Success\s+and\s+Failure|Failure\s+and\s+Success|Success|Failure)\s*$/i;
const guidAtEndPattern = /\s*\{[0-9a-f-]{30,40}\}\s*$/i;

function normaliseSetting(value: string): string {
  const clean = value.trim().replace(/\s+/g, ' ');
  if (/^failure and success$/i.test(clean)) return 'Success and Failure';
  if (/^no auditing$/i.test(clean)) return 'No Auditing';
  if (/^success and failure$/i.test(clean)) return 'Success and Failure';
  if (/^success$/i.test(clean)) return 'Success';
  if (/^failure$/i.test(clean)) return 'Failure';
  return clean;
}

function compareSetting(expected: string, actual: string): CommunityStatus {
  if (!actual) return 'Not found';
  if (expected === actual) return 'Aligned';
  if (actual === 'No Auditing') return 'Gap';
  if (actual === 'Success and Failure' && (expected === 'Success' || expected === 'Failure')) return 'Partial';
  if (expected === 'Success and Failure' && (actual === 'Success' || actual === 'Failure')) return 'Partial';
  return 'Partial';
}

function detectRole(raw: string): CommunityRole | null {
  if (/\b(domain controller|directory service changes|ds access|active directory)\b/i.test(raw)) return 'DC';
  if (/\bwindows server\b/i.test(raw)) return 'Server';
  if (/\bwindows (?:10|11)\b/i.test(raw)) return 'Workstation';
  return null;
}

function detectOperatingSystem(raw: string): CommunityOperatingSystem | null {
  const candidates: Array<[RegExp, CommunityOperatingSystem]> = [
    [/\bwindows server 2025\b/i, 'Windows Server 2025'],
    [/\bwindows server 2022\b/i, 'Windows Server 2022'],
    [/\bwindows server 2019\b/i, 'Windows Server 2019'],
    [/\bwindows server 2016\b/i, 'Windows Server 2016'],
    [/\bwindows 11\b/i, 'Windows 11'],
    [/\bwindows 10\b/i, 'Windows 10']
  ];
  return candidates.find(([pattern]) => pattern.test(raw))?.[1] ?? null;
}

function sanitiseAssetName(value: string): string {
  return value.trim().replace(/[<>"'`]/g, '').replace(/\s+/g, ' ').slice(0, 80) || 'COMMUNITY-ASSET';
}

function extractAssetNames(lines: string[]): string[] {
  const values: string[] = [];
  const pattern = /^\s*(?:Asset|Host|Hostname|Computer|Computer Name|Machine|Machine Name|Server|DC)\s*[:=]\s*(.+?)\s*$/i;
  for (const line of lines) {
    const match = line.match(pattern);
    if (match?.[1]) values.push(sanitiseAssetName(match[1]));
  }
  return [...new Set(values.map(value => value.toLowerCase()))].map(lower => values.find(value => value.toLowerCase() === lower) as string);
}

export function assessCommunityEvidence(
  raw: string,
  requestedRole: CommunityRoleChoice = 'Auto',
  requestedOperatingSystem: CommunityOperatingSystemChoice = 'Auto'
): CommunityAssessmentResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const cleanRaw = raw.replace(/^\uFEFF/, '');
  const evidenceBytes = new TextEncoder().encode(cleanRaw).byteLength;

  if (!cleanRaw.trim()) return { assessment: null, errors: ['Add one auditpol evidence file or paste its text before running the assessment.'], warnings };
  if (evidenceBytes > COMMUNITY_MAX_EVIDENCE_BYTES) errors.push('Community accepts one text evidence item up to 1 MB. Reduce the file or use TAS Professional for larger assessments.');

  const lines = cleanRaw.replace(/\r\n?/g, '\n').split('\n');
  const assetNames = extractAssetNames(lines);
  if (assetNames.length > 1) errors.push(`Community accepts one asset per assessment. This evidence appears to contain ${assetNames.length} assets.`);

  const settings = new Map<string, string>();
  const categoriesSeen = new Set<string>();
  let duplicateSettings = 0;
  let category = '';

  for (const line of lines) {
    const trimmed = line.trim();
    const categoryMatch = categoryAliases.get(trimmed.toLowerCase().replace(/:$/, ''));
    if (categoryMatch) {
      category = categoryMatch;
      categoriesSeen.add(categoryMatch);
      continue;
    }

    const settingMatch = line.match(settingAtEndPattern);
    if (!settingMatch || !category) continue;
    const actual = normaliseSetting(settingMatch[1]);
    const prefix = line.slice(0, settingMatch.index).trim().replace(guidAtEndPattern, '').trim();
    if (!prefix || /^category\/subcategory$/i.test(prefix)) continue;
    const key = `${category}::${prefix}`.toLowerCase();
    if (settings.has(key)) duplicateSettings += 1;
    settings.set(key, actual);
  }

  if (!settings.size) errors.push('No recognisable Advanced Audit Policy settings were found. Use text produced by auditpol /get /category:* or load the safe demonstration.');
  if (errors.length) return { assessment: null, errors, warnings };

  const detectedRole = detectRole(cleanRaw);
  const role = requestedRole === 'Auto' ? (detectedRole ?? 'Workstation') : requestedRole;
  const detectedOperatingSystem = detectOperatingSystem(cleanRaw);
  const operatingSystem = requestedOperatingSystem === 'Auto'
    ? (detectedOperatingSystem ?? (role === 'Workstation' ? 'Windows 11' : 'Windows Server 2022'))
    : requestedOperatingSystem;

  if (requestedRole === 'Auto' && !detectedRole) warnings.push(`Asset role was not present in the evidence. Community used ${role}; review and change it if needed.`);
  if (requestedOperatingSystem === 'Auto' && !detectedOperatingSystem) warnings.push(`Operating system was not present in the evidence. Community used ${operatingSystem}; review and change it if needed.`);
  if (duplicateSettings) warnings.push(`${duplicateSettings} duplicate audit setting${duplicateSettings === 1 ? ' was' : 's were'} found; the last value was assessed.`);

  const controls = communityControls.filter(control => !control.roles || control.roles.includes(role));
  const findings = controls.map(control => {
    const actual = settings.get(`${control.category}::${control.subcategory}`.toLowerCase()) || '';
    return { ...control, actual: actual || 'Not found', status: compareSetting(control.expected, actual) };
  });

  const aligned = findings.filter(item => item.status === 'Aligned').length;
  const partial = findings.filter(item => item.status === 'Partial').length;
  const gap = findings.filter(item => item.status === 'Gap').length;
  const notFound = findings.filter(item => item.status === 'Not found').length;
  const score = findings.length ? Math.round(((aligned + partial * 0.5) / findings.length) * 100) : 0;
  const notices = [
    `Community assessed ${findings.length} selected controls for one ${role}.`,
    'Framework labels are selected assurance perspectives, not certification or a complete benchmark assessment.',
    'Raw evidence remains in this browser session and is not included in the downloaded report.'
  ];

  return {
    assessment: {
      assetName: assetNames[0] ?? 'COMMUNITY-ASSET',
      role,
      operatingSystem,
      roleWasDetected: requestedRole === 'Auto' && Boolean(detectedRole),
      operatingSystemWasDetected: requestedOperatingSystem === 'Auto' && Boolean(detectedOperatingSystem),
      findings,
      aligned,
      partial,
      gap,
      notFound,
      score,
      parseStats: {
        linesRead: lines.length,
        recognisedSettings: settings.size,
        duplicateSettings,
        categoriesSeen: categoriesSeen.size
      },
      notices
    },
    errors,
    warnings
  };
}

export async function sha256Evidence(raw: string): Promise<string> {
  const bytes = new TextEncoder().encode(raw.replace(/^\uFEFF/, ''));
  if (!globalThis.crypto?.subtle) return 'SHA-256 unavailable in this browser';
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest), value => value.toString(16).padStart(2, '0')).join('');
}

export const communitySample = `Asset: TAS-COMMUNITY-DEMO
Operating System: Windows Server 2022
Role: Member Server
System
  Security System Extension                  Success
  System Integrity                           Success and Failure
Logon/Logoff
  Logon                                      Success and Failure
  Logoff                                     Success
  Account Lockout                            No Auditing
Detailed Tracking
  Process Creation                           Success
Policy Change
  Audit Policy Change                        Success
  Authentication Policy Change               Success
Account Management
  User Account Management                    Success
  Security Group Management                  Success
Account Logon
  Credential Validation                      Success and Failure`;
