import { useEffect, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Download, ExternalLink, FileCheck2, Fingerprint, LockKeyhole, Menu, ShieldCheck, Sparkles, X } from 'lucide-react';
import CommunityApp from '../community/CommunityApp';
import '../community/community.css';
import './public.css';

type Route = '/' | '/community' | '/studio' | '/professional' | '/consultant' | '/assessments' | '/pricing' | '/trust' | '/downloads' | '/knowledge' | '/support-development' | '/legal';
const nav: Array<[string, Route]> = [['Product','/'],['Community','/community'],['Professional','/professional'],['Assessments','/assessments'],['Pricing','/pricing'],['Trust','/trust']];

function route(): Route { const p = window.location.pathname.replace(/\/$/, '') || '/'; return (['/','/community','/studio','/professional','/consultant','/assessments','/pricing','/trust','/downloads','/knowledge','/support-development','/legal'].includes(p) ? p : '/') as Route; }
function go(path: Route) { history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({top:0, behavior:'smooth'}); }

const Button = ({to, children, secondary=false}:{to:Route;children:React.ReactNode;secondary?:boolean}) => <button className={secondary?'siteButton secondary':'siteButton'} onClick={()=>go(to)}>{children}</button>;

function Home(){return <>
<section className="siteHero"><div className="heroGlow"/><div className="heroCopy"><span className="eyebrow"><Sparkles size={15}/> Windows telemetry assurance, made defensible</span><h1>Turn raw Windows audit evidence into <em>defensible security assurance.</em></h1><p>TAS converts auditpol evidence into clear findings, framework-alignment views and management-ready reporting — without sending customer evidence to a server.</p><div className="heroActions"><Button to="/studio">Run TAS Community <ArrowRight size={17}/></Button><Button to="/professional" secondary>Explore Professional</Button></div><div className="trustStrip"><span><LockKeyhole/>Browser-local by default</span><span><FileCheck2/>Evidence-led findings</span><span><Fingerprint/>No account for Community</span></div></div><div className="heroPanel"><div className="panelTop"><span>TELEMETRY ASSURANCE STUDIO</span><b>Selected posture</b></div><div className="scoreRing"><strong>82%</strong><span>Assurance score</span></div><div className="miniStats"><div><b>36</b><span>Aligned</span></div><div><b>7</b><span>Partial</span></div><div><b>5</b><span>Gaps</span></div></div><div className="finding"><ShieldCheck/><span><b>Audit Process Creation</b><small>Aligned · Microsoft · CIS · NIST</small></span></div><div className="finding warn"><ShieldCheck/><span><b>Credential Validation</b><small>Partial · remediation available</small></span></div></div></section>
<section className="section"><div className="sectionHead"><span>ONE ENGINE · THREE WAYS TO USE IT</span><h2>Start free. Move up when the work becomes commercial.</h2></div><div className="cardGrid three"><article><span className="cardTag">FREE</span><h3>TAS Community</h3><p>A useful first assessment for one Windows asset, selected controls and a watermarked HTML report.</p><Button to="/studio">Run Community</Button></article><article className="featured"><span className="cardTag">MAIN PRODUCT</span><h3>TAS Professional</h3><p>Full standalone assurance, Golden comparison, Before and After validation and unrestricted reporting.</p><Button to="/professional">View Professional</Button></article><article><span className="cardTag">COMMERCIAL USE</span><h3>TAS Consultant</h3><p>Client-assessment rights, consultant branding and repeatable remediation packs.</p><Button to="/consultant">View Consultant</Button></article></div></section>
<section className="section darkBand"><div><span>BUILT FOR TRUST</span><h2>Your evidence is not our product.</h2><p>Community processing is browser-local. TAS does not need customer audit evidence to create value, and Professional is designed to operate locally without Cloudflare.</p></div><Button to="/trust">Read the trust position <ArrowRight size={16}/></Button></section>
<section className="section"><div className="sectionHead"><span>FROM CONFIGURATION TO DECISION</span><h2>More than a policy viewer.</h2></div><div className="featureGrid">{[['Evidence intake','Parse auditpol output and identify asset context.'],['Golden comparison','Compare multiple assets against one trusted baseline.'],['Before and After','Prove whether remediation delivered the intended change.'],['Event intelligence','Connect audit settings to the Windows events defenders need.'],['Framework lenses','Present relevant Microsoft, CIS and NIST alignment.'],['Management reporting','Turn technical gaps into prioritised, readable evidence.']].map(([a,b])=><article key={a}><Check/><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></section>
</>}

function Page({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <main><section className="pageHero"><span>{kicker}</span><h1>{title}</h1></section><section className="pageBody">{children}</section></main>}
function Pricing(){return <Page kicker="CLEAR EDITIONS" title="Choose the capability that matches the work."><div className="pricingGrid">{[
['Community','Free','One asset per assessment',['Selected assurance controls','Watermarked HTML report','No account required'],'/studio' as Route],
['Professional','£149','Introductory purchase · 12 months updates',['Full standalone capability','Golden and Before/After comparison','Complete reporting pack'],'/professional' as Route],
['Consultant','£399 / year','Commercial client-assessment edition',['Commercial usage rights','Consultant branding','Client remediation packs'],'/consultant' as Route]
].map(([n,p,d,items,to])=><article className={n==='Professional'?'price featured':'price'} key={n as string}><span>{n}</span><h2>{p}</h2><p>{d}</p><ul>{(items as string[]).map(i=><li key={i}><Check/> {i}</li>)}</ul><Button to={to as Route}>{n==='Community'?'Run free':'View edition'}</Button></article>)}</div><p className="finePrint">Team and Enterprise remain enquiry-led. Payment integration is intentionally deferred to the commerce sprint.</p></Page>}
function Trust(){return <Page kicker="PRIVACY AND EVIDENCE HANDLING" title="Security assurance should not create another evidence risk."><div className="proseGrid"><article><LockKeyhole/><h3>Browser-local Community</h3><p>The active Community assessment is processed in the browser. No evidence-upload endpoint is required.</p></article><article><Fingerprint/><h3>Evidence receipt</h3><p>A local SHA-256 receipt identifies the assessed input without embedding raw evidence in the report.</p></article><article><ShieldCheck/><h3>Local Professional operation</h3><p>The paid standalone product is designed to work locally, independently of the public website.</p></article><article><FileCheck2/><h3>Truthful output</h3><p>TAS distinguishes aligned, partial, gap and missing evidence states. It does not fabricate unavailable results.</p></article></div></Page>}
function Product({kind}:{kind:'community'|'professional'|'consultant'}){const c={community:['TAS Community','A genuinely useful free first step.','Assess one Windows asset with selected controls and produce a restrained watermarked report.'],professional:['TAS Professional','The complete standalone assurance product.','Use full baseline intelligence, multi-asset Golden comparison, Before and After validation and complete management reporting.'],consultant:['TAS Consultant','Professional capability with commercial client rights.','Run repeatable client assessments, add consultant identity and export clear remediation packs.']}[kind];return <Page kicker="TELEMETRY ASSURANCE STUDIO" title={c[0]}><div className="productIntro"><div><h2>{c[1]}</h2><p>{c[2]}</p><div className="heroActions">{kind==='community'?<Button to="/studio">Run Community</Button>:<Button to="/downloads">Release information</Button>}<Button to="/pricing" secondary>Compare editions</Button></div></div><div className="productMark"><ShieldCheck/><span>{kind.toUpperCase()}</span></div></div></Page>}
function Assessments(){return <Page kicker="EXPERT SERVICES" title="Add professional interpretation when the decision matters."><div className="cardGrid three"><article><h3>TAS Express Review</h3><p>Sanitised evidence review, technical assurance report, management summary and prioritised remediation plan.</p><b>Planned £299–£350</b></article><article><h3>Baseline Assessment</h3><p>Multiple systems or domains, Golden comparison, framework mapping and a remediation meeting.</p><b>Scoped engagement</b></article><article><h3>Custom Golden Baseline</h3><p>Customer-specific expectations, governance rationale, baseline pack and validation methodology.</p><b>Scoped engagement</b></article></div><div className="notice">Evidence submission is not enabled in this sprint. No evidence will be accepted without explicit scope, handling and retention terms.</div></Page>}
function Downloads(){return <Page kicker="CONTROLLED RELEASES" title="Downloads will be published with identity, hashes and release evidence."><div className="downloadCard"><Download/><div><h3>TAS Community v70.21</h3><p>The public Community Studio is available directly in the browser. Packaged customer downloads remain controlled until commerce and fulfilment are connected.</p></div><Button to="/studio">Open Studio</Button></div><div className="notice">Professional and Consultant download buttons are deliberately not public placeholders. Protected fulfilment arrives with licensing and commerce.</div></Page>}
function Simple({type}:{type:'knowledge'|'support'|'legal'}){const map={knowledge:['Knowledge Centre','Original Windows telemetry guidance is being prepared.','Articles will cover audit policy, Domain Controller events, Golden baselines, SIEM visibility and evidence sanitisation.'],support:['Support TAS Development','A restrained voluntary support option will arrive later.','It will never appear in Professional or Consultant, reports, checkout or controlled downloads.'],legal:['Legal and product terms','Commercial legal documents are not yet presented as final.','Terms, privacy, cookies, refunds and EULA will be completed before payments or public commercial fulfilment are enabled.']}[type];return <Page kicker="AUDITPOL.COM" title={map[0]}><div className="singleProse"><h2>{map[1]}</h2><p>{map[2]}</p></div></Page>}

export default function PublicApp(){const [path,setPath]=useState<Route>(route());const [open,setOpen]=useState(false);useEffect(()=>{const fn=()=>{setPath(route());setOpen(false)};addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]);if(path==='/studio')return <div><button className="studioBack" onClick={()=>go('/')}><ArrowRight/> Back to AuditPol.com</button><CommunityApp/></div>;let content:React.ReactNode=<Home/>;if(path==='/pricing')content=<Pricing/>;else if(path==='/trust')content=<Trust/>;else if(path==='/community')content=<Product kind="community"/>;else if(path==='/professional')content=<Product kind="professional"/>;else if(path==='/consultant')content=<Product kind="consultant"/>;else if(path==='/assessments')content=<Assessments/>;else if(path==='/downloads')content=<Downloads/>;else if(path==='/knowledge')content=<Simple type="knowledge"/>;else if(path==='/support-development')content=<Simple type="support"/>;else if(path==='/legal')content=<Simple type="legal"/>;return <div className="siteShell"><header className="siteHeader"><button className="brand" onClick={()=>go('/')}><ShieldCheck/><span><b>AuditPol</b><small>TELEMETRY ASSURANCE STUDIO</small></span></button><nav className={open?'open':''}>{nav.map(([label,to])=><button className={path===to?'active':''} key={to} onClick={()=>go(to)}>{label}</button>)}<Button to="/studio">Run Community</Button></nav><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{content}<footer><div className="brand footerBrand"><ShieldCheck/><span><b>AuditPol</b><small>TELEMETRY ASSURANCE STUDIO</small></span></div><div>{[['Community','/community'],['Pricing','/pricing'],['Trust','/trust'],['Downloads','/downloads'],['Knowledge','/knowledge'],['Legal','/legal']].map(([l,p])=><button key={p} onClick={()=>go(p as Route)}>{l}</button>)}</div><p>© 2026 AuditPol · Evidence-led Windows telemetry assurance</p></footer></div>}
